export const CAUSES = [
  {
    id: 'competition-awards',
    title: 'Competition Awards',
    emoji: '🏆',
    description: 'Fund prizes for annual science and innovation competitions that motivate African youth to push the boundaries of discovery.',
    target: 25000,
    raised: 18750,
    color: 'bg-amber-50 border-amber-200',
  },
  {
    id: 'innovation-dev',
    title: 'Innovation Development',
    emoji: '💡',
    description: 'Support early-stage African innovations with prototyping grants, mentorship, and technical resources to bring ideas to market.',
    target: 50000,
    raised: 31200,
    color: 'bg-blue-50 border-blue-200',
  },
  {
    id: 'research-support',
    title: 'Research Support',
    emoji: '🔬',
    description: 'Provide researchers with equipment, reagents, and publication support to advance critical studies across the continent.',
    target: 40000,
    raised: 22800,
    color: 'bg-purple-50 border-purple-200',
  },
  {
    id: 'student-programs',
    title: 'Student Programs',
    emoji: '🎓',
    description: 'Sponsor scholarships, internships, and STEM bootcamps that prepare the next generation of African scientists and technologists.',
    target: 30000,
    raised: 19500,
    color: 'bg-emerald-50 border-emerald-200',
  },
  {
    id: 'general',
    title: 'General Support',
    emoji: '🌍',
    description: 'Support our network\'s internal framework and enlightenment programs across the African continent.',
    target: 100000,
    raised: 45000,
    color: 'bg-indigo-50 border-indigo-200',
  },
];

export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£E' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'DH' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
];
